#!/bin/sh
. ~/.config/HyprV/hyprv.conf

# Check which waybar theme is set
THEMEIS=$(readlink -f ~/.config/waybar/style.css | cut -d '-' -f2)

#if the theme is not dark then we need to switch to it
if [[ $THEMEIS == "light.css" ]]; then
    SWITCHTO="dark"
    MODESTR="Dark"
    GNOMETHEME="-dark"
else
    SWITCHTO="light" 
    MODESTR="Light"
    GNOMETHEME=""
fi

#set the waybar theme
ln -sf ~/.config/HyprV/waybar/style/theme-$SWITCHTO.css ~/.config/waybar/style.css

#set the wofi theme
ln -sf ~/.config/HyprV/wofi/style/$SWITCHTO.css ~/.config/wofi/style.css

#set the mako theme
ln -sf ~/.config/HyprV/mako/conf/config-$SWITCHTO ~/.config/mako/config

#ln -sf ~/.config/HyprV/waybar/conf/mesu-met.jsonc ~/.config/HyprV/waybar/conf/mesu.jsonc

xfconf-query -c xsettings -p /Net/IconThemeName -s "Adwaita"$GNOMETHEME
gsettings set org.gnome.desktop.interface icon-theme "Adwaita"$GNOMETHEME
xfconf-query -c xsettings -p /Net/ThemeName -s "Adwaita"$GNOMETHEME
gsettings set org.gnome.desktop.interface gtk-theme "Adwaita"$GNOMETHEME


#change the background image and be cool about it ;)
if [ -z $SET_BG ]; then
    swww img ~/.config/HyprV/backgrounds/'background'$SWITCHTO.jpg --transition-fps 60 --transition-type wipe --transition-duration 2
else
    swww img $SET_BG --transition-fps 60 --transition-type wipe --transition-duration 2
fi

#update the sddm image
cp -f ~/.config/HyprV/backgrounds/'background-'$SWITCHTO.jpg /usr/share/sddm/themes/sdt/wallpaper.jpg

#reset mako
sleep 1
pkill mako
mako &

#sleep 1;
#swww kill 
#swww init

#restart the waybar
#killall -SIGUSR2 waybar <-- start causing web brwsers to close so switched to below...
pkill waybar
waybar &

